name: Build and Test

on:
  push:
    branches:
    - 'master'
    - 'develop'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  coverage:
    name: coverage (ubuntu-18.04)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Coverage -DASAN=ON -DUBSAN=ON -DLSAN=ON -DWERROR=ON -j 2 -Bbuild -H.
      - name: build
        run: cmake --build build -j 2
      - name: test
        run: ./build/src/unit_tests_runner
      - name: run lcov
        run: lcov --capture --directory . --output-file lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"

  ubuntu18-non-superbuild:
    name: ubuntu-18.04 (non-backend, non-superbuild)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install
        run: sudo apt-get update && sudo apt-get install -y libjsoncpp-dev libcurl4-openssl-dev libtinyxml2-dev
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DSUPERBUILD=OFF -DWERROR=ON -j 2 -Bbuild/release -H.
      - name: build
        run: cmake --build build/release -j 2
      - name: test
        run: ./build/release/src/unit_tests_runner

  ubuntu18-superbuild:
    name: ubuntu-18.04 (backend, superbuild)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DSUPERBUILD=ON -DBUILD_BACKEND=ON -DWERROR=ON -j 2 -Bbuild/release -H.
      - name: build
        run: cmake --build build/release -j 2
      - name: install
        run: sudo cmake --build build/release --target install
      - name: install examples dependencies
        run: sudo apt-get install -y libsdl2-dev
      - name: configure examples
        run: (cd examples && cmake -DCMAKE_BUILD_TYPE=Release -DWERROR=ON -j 2 -Bbuild -H.)
      - name: build examples
        run: (cd examples && cmake --build build -j 2)
      - name: test
        run: ./build/release/src/unit_tests_runner
      - name: test (mavsdk_server)
        run: ./build/release/src/backend/test/unit_tests_backend

  ubuntu20-proto-check:
    name: ubuntu-20.04 (proto check)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install clang-format
        run: sudo apt-get install -y clang-format-10
      - name: install dcsdkgen
        run: |
             cd proto/pb_plugins
             pip3 install --user -r requirements.txt
             pip3 install --user -e .
      - name: build necessary protoc tooling
        run: cmake -DBUILD_BACKEND=ON -Bbuild/default -H.
      - name: generate code from protos
        run: PATH="$PATH:$HOME/.local/bin" tools/generate_from_protos.sh
      - name: fix style
        run: tools/fix_style.sh . || true
      - name: check for diff
        run: git diff --exit-code

  ubuntu20-check-style:
    name: ubuntu-20.04 (check style and docs)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: sudo apt-get install -y doxygen clang-format-10
      - name: check style
        run: ./tools/fix_style.sh .
      - name: check docs
        run: tools/generate_docs.sh

  dockcross-linux:
    name: ${{ matrix.arch_name }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch_name: [linux-arm64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.arch_name }} > ./dockcross-${{ matrix.arch_name }}; chmod +x ./dockcross-${{ matrix.arch_name }}
      - name: configure
        run: ./dockcross-${{ matrix.arch_name }} cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/${{ matrix.arch_name }}/install -DBUILD_BACKEND=ON -DBUILD_SHARED_LIBS=OFF -DWERROR=ON -j 2 -Bbuild/${{ matrix.arch_name }} -H.
      - name: build
        run: ./dockcross-${{ matrix.arch_name }} cmake --build build/${{ matrix.arch_name }} -j 2 --target install
      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/${{ matrix.arch_name }}/install/bin/mavsdk_server'
          asset_name: 'mavsdk_server_${{ matrix.arch_name }}'
          tag: ${{ github.ref }}
          overwrite: true

  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/release/install -DBUILD_BACKEND=ON -DBUILD_SHARED_LIBS=OFF -DWERROR=ON -j 2 -Bbuild/release -H.
      - name: build
        run: cmake --build build/release -j 2 --target install
      - name: test (core)
        run: ./build/release/src/unit_tests_runner
      - name: test (mavsdk_server)
        run: ./build/release/src/backend/test/unit_tests_backend
      - name: Publish artefacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/release/install/bin/mavsdk_server'
          asset_name: 'mavsdk_server_macos'
          tag: ${{ github.ref }}
          overwrite: true

